services:
  
  httpservice:
    build:
      context: .  # Path to the HttpService Dockerfile
      dockerfile: ./http/Dockerfile
    ports:
      - "8080:8080"  # Map your computer's port 8080 to the container's port 8080
    environment:
      # This is how you pass configuration.
      # Docker Compose creates a network where the container 'someservice'
      # can be reached just by its name.
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__SomeService=http://someservice:8080
    depends_on:
      - someservice # Tells Docker to start someservice *before* this one

  # This is your 'someService' gRPC service
  someservice:
    build:
      context: .  # Path to the SomeService Dockerfile
      dockerfile: ./SomeService/Dockerfile
    ports:
      - "8081:8080" # Map your computer's port 8081 (to avoid conflict)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development