volumes:
  mongo_data:

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  httpservice:
    build:
      context: .  # Path to the HttpService Dockerfile
      dockerfile: ./http/Dockerfile
    ports:
      - "8080:8080"  # Map your computer's port 8080 to the container's port 8080
    environment:
      # This is how you pass configuration.
      # Docker Compose creates a network where the container 'someservice'
      # can be reached just by its name.
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
      - Logging__SeqUrl=http://seq
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System.Net.Http=Warning
      - Logging__LogLevel__Grpc=Warnin
    depends_on:
      - users
      - email
      - excel
      - seq

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"   # Expose the Seq UI on your computer at port 5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - Logging__SeqUrl=http://seq
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
    depends_on:
      - email
      - excel
      - seq

  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq
  
  excel:
    build:
      context: .
      dockerfile: ./excel/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=excel
    depends_on:
      - seq
    volumes:
      - ./FileStorage:/app/FileStorage