services:
  httpservice:
    build:
      context: .  # Path to the HttpService Dockerfile
      dockerfile: ./http/Dockerfile
    ports:
      - "8080:8080"  # Map your computer's port 8080 to the container's port 8080
    environment:
      # This is how you pass configuration.
      # Docker Compose creates a network where the container 'someservice'
      # can be reached just by its name.
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__SomeService=http://someservice:8080
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
      - Logging__SeqUrl=http://seq
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System.Net.Http=Warning
      - Logging__LogLevel__Grpc=Warnin
    depends_on:
      - someservice # Tells Docker to start someservice *before* this one
      - users
      - email
      - seq

  # This is your 'someService' gRPC service
  someservice:
    build:
      context: .  # Path to the SomeService Dockerfile
      dockerfile: ./SomeService/Dockerfile
    ports:
      - "8081:8080" # Map your computer's port 8081 (to avoid conflict)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System.Net.Http=Warning
      - Logging__LogLevel__Grpc=Warnin
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"   # Expose the Seq UI on your computer at port 5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq

  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq
