volumes:
  mongo_data:

networks:
  campus-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    restart: always
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - campus-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
    networks:
      - campus-network

  http:
    build:
      context: .
      dockerfile: ./http/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - GrpcServices__AnnouncementsService=http://announcements:8080
      - GrpcServices__ChatService=http://chat:8080 
      - GrpcServices__GradesService=http://grades:8080 
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
      - Logging__SeqUrl=http://seq
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System.Net.Http=Warning
      - Logging__LogLevel__Grpc=Warning
    depends_on:
      - users
      - email
      - excel
      - chat
      - announcements
      - seq
      - grades 
    networks:
      - campus-network

  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    logging:
      driver: none
    tmpfs:
      - /data
    networks:
      - campus-network

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - Logging__SeqUrl=http://seq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=users
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
    depends_on:
      - email
      - excel
      - seq
      - mongo
    networks:
      - campus-network

  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq
    networks:
      - campus-network
  
  excel:
    build:
      context: .
      dockerfile: ./excel/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=excel
    depends_on:
      - seq
      - mongo
    volumes:
      - ./FileStorage:/app/FileStorage
    networks:
      - campus-network
  
  chat:
    build:
      context: .
      dockerfile: ./chat/Dockerfile
    ports:
      - "8084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - Logging__SeqUrl=http://seq
      - RabbitMq__Host=rabbitmq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=chat
    depends_on:
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_started
      users:
        condition: service_started
      mongo:
        condition: service_started
    volumes:
      - ./FileStorage:/app/FileStorage
    networks:
      - campus-network

  notification:
    build:
      context: .
      dockerfile: ./notification/Dockerfile
    ports:
      - "8085:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__ChatService=http://chat:8080
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
      - Logging__SeqUrl=http://seq
      - RabbitMq__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_started
      chat:
        condition: service_started
      email:
        condition: service_started
    networks:
      - campus-network


  announcements:
    build:
      context: .
      dockerfile: ./announcements/Dockerfile
    ports:
      - "8087:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=announcements
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
    depends_on:
      - seq
      - mongo
      - users
      - email
    networks:
      - campus-network

  grades:
    build:
      context: .
      dockerfile: ./grades/Dockerfile
    ports:
      - "8089:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=grades
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq
      - mongo
      - users
      - excel
      - email 
    networks:
      - campus-network
