volumes:
  mongo_data:

networks:
  campus-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - campus-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - campus-network

  http:
    build:
      context: .
      dockerfile: ./http/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - GrpcServices__ChatService=http://chat:8080 
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
      - Logging__SeqUrl=http://seq
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System.Net.Http=Warning
      - Logging__LogLevel__Grpc=Warning
    depends_on:
      - users
      - email
      - excel
      - chat
      - seq
    networks:
      - campus-network

  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    networks:
      - campus-network

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__EmailService=http://email:8080 
      - GrpcServices__ExcelService=http://excel:8080
      - Logging__SeqUrl=http://seq
      - SecretKey=a_very_secret_key_that_must_be_long_and_complex
    depends_on:
      - email
      - excel
      - seq
    networks:
      - campus-network

  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
    depends_on:
      - seq
    networks:
      - campus-network
  
  excel:
    build:
      context: .
      dockerfile: ./excel/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=excel
    depends_on:
      - seq
    volumes:
      - ./FileStorage:/app/FileStorage
    networks:
      - campus-network
  
  chat:
    build:
      context: .
      dockerfile: ./chat/Dockerfile
    ports:
      - "8084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__UsersService=http://users:8080
      - Logging__SeqUrl=http://seq
      - RabbitMq__Host=rabbitmq
      - MongoDB__ConnectionString=mongodb://mongo:27017/
      - MongoDB__DatabaseName=chat
    depends_on:
      - seq
      - users
      - rabbitmq
    volumes:
      - ./FileStorage:/app/FileStorage
    networks:
      - campus-network

  notification:
    build:
      context: .
      dockerfile: ./notification/Dockerfile
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__SeqUrl=http://seq
      - RabbitMq__Host=rabbitmq
    depends_on:
      - seq
      - rabbitmq
    networks:
      - campus-network